
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000

    image: app:django
    container_name: django-container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
   image: postgres:16
   volumes:
     - db_data:/var/lib/postgresql/data

   ports:
     - '5432:5432'

   environment:
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   container_name: postgres_db1


volumes:
  db_data:
